"""add cascade deletes

Revision ID: 304871eadf7b
Revises: 57008c1fe4fd
Create Date: 2026-03-29 17:30:44.911918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '304871eadf7b'
down_revision: Union[str, Sequence[str], None] = '57008c1fe4fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agent', 'workflow_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agent', 'workflow_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
