"""add config in Agents

Revision ID: a47415c8d471
Revises: f738964e2b16
Create Date: 2026-03-30 01:53:14.899535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a47415c8d471'
down_revision: Union[str, Sequence[str], None] = 'f738964e2b16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent', sa.Column('config', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'agent', 'nodeconfig', ['config'], ['id'])
    op.alter_column('handoff', 'workflow_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('nodeconfig', 'workflow_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('positionnode', 'workflow_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('tool', 'workflow_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tool', 'workflow_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('positionnode', 'workflow_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('nodeconfig', 'workflow_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('handoff', 'workflow_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'agent', type_='foreignkey')
    op.drop_column('agent', 'config')
    # ### end Alembic commands ###
