"""add adges

Revision ID: bd5f2c0c2ebd
Revises: 
Create Date: 2026-04-05 00:11:15.301919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bd5f2c0c2ebd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edge',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.Uuid(), nullable=False),
    sa.Column('target', sa.Uuid(), nullable=False),
    sa.Column('workflow_id', sa.Uuid(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['source'], ['positionnode.id'], ),
    sa.ForeignKeyConstraint(['target'], ['positionnode.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('edge')
    # ### end Alembic commands ###
