"""some migrations

Revision ID: e4c9b6712779
Revises: 6c8f5c6d0d9b
Create Date: 2026-03-29 13:28:15.303940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e4c9b6712779'
down_revision: Union[str, Sequence[str], None] = '6c8f5c6d0d9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('agent_config_fkey'), 'agent', type_='foreignkey')
    op.drop_column('agent', 'config')
    op.add_column('handoff', sa.Column('workflow_id', sa.Uuid(), nullable=False))
    op.drop_constraint(op.f('handoff_Workflow_id_fkey'), 'handoff', type_='foreignkey')
    op.create_foreign_key(None, 'handoff', 'workflow', ['workflow_id'], ['id'])
    op.drop_column('handoff', 'Workflow_id')
    op.add_column('nodeconfig', sa.Column('workflow_id', sa.Uuid(), nullable=False))
    op.add_column('nodeconfig', sa.Column('agent_id', sa.Uuid(), nullable=True))
    op.add_column('nodeconfig', sa.Column('tool_id', sa.Uuid(), nullable=True))
    op.drop_constraint(op.f('nodeconfig_Workflow_id_fkey'), 'nodeconfig', type_='foreignkey')
    op.create_foreign_key(None, 'nodeconfig', 'workflow', ['workflow_id'], ['id'])
    op.create_foreign_key(None, 'nodeconfig', 'agent', ['agent_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'nodeconfig', 'tool', ['tool_id'], ['id'], ondelete='CASCADE')
    op.drop_column('nodeconfig', 'Workflow_id')
    op.add_column('positionnode', sa.Column('agent_id', sa.Uuid(), nullable=True))
    op.add_column('positionnode', sa.Column('tool_id', sa.Uuid(), nullable=True))
    op.alter_column('positionnode', 'workflow_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('positionnode_Workflow_id_fkey'), 'positionnode', type_='foreignkey')
    op.drop_constraint(op.f('fk_positionnode_workflow_id_workflow'), 'positionnode', type_='foreignkey')
    op.create_foreign_key(None, 'positionnode', 'agent', ['agent_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'positionnode', 'tool', ['tool_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'positionnode', 'workflow', ['workflow_id'], ['id'])
    op.drop_column('positionnode', 'Workflow_id')
    op.add_column('tool', sa.Column('workflow_id', sa.Uuid(), nullable=False))
    op.add_column('tool', sa.Column('agent_id', sa.Uuid(), nullable=False))
    op.drop_constraint(op.f('tool_Workflow_id_fkey'), 'tool', type_='foreignkey')
    op.drop_constraint(op.f('tool_position_fkey'), 'tool', type_='foreignkey')
    op.drop_constraint(op.f('tool_config_fkey'), 'tool', type_='foreignkey')
    op.create_foreign_key(None, 'tool', 'workflow', ['workflow_id'], ['id'])
    op.create_foreign_key(None, 'tool', 'agent', ['agent_id'], ['id'])
    op.drop_column('tool', 'config')
    op.drop_column('tool', 'Workflow_id')
    op.drop_column('tool', 'position')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tool', sa.Column('position', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('tool', sa.Column('Workflow_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('tool', sa.Column('config', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tool', type_='foreignkey')
    op.drop_constraint(None, 'tool', type_='foreignkey')
    op.create_foreign_key(op.f('tool_config_fkey'), 'tool', 'nodeconfig', ['config'], ['id'])
    op.create_foreign_key(op.f('tool_position_fkey'), 'tool', 'positionnode', ['position'], ['id'])
    op.create_foreign_key(op.f('tool_Workflow_id_fkey'), 'tool', 'workflow', ['Workflow_id'], ['id'])
    op.drop_column('tool', 'agent_id')
    op.drop_column('tool', 'workflow_id')
    op.add_column('positionnode', sa.Column('Workflow_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'positionnode', type_='foreignkey')
    op.drop_constraint(None, 'positionnode', type_='foreignkey')
    op.drop_constraint(None, 'positionnode', type_='foreignkey')
    op.create_foreign_key(op.f('fk_positionnode_workflow_id_workflow'), 'positionnode', 'workflow', ['workflow_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('positionnode_Workflow_id_fkey'), 'positionnode', 'workflow', ['Workflow_id'], ['id'])
    op.alter_column('positionnode', 'workflow_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('positionnode', 'tool_id')
    op.drop_column('positionnode', 'agent_id')
    op.add_column('nodeconfig', sa.Column('Workflow_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'nodeconfig', type_='foreignkey')
    op.drop_constraint(None, 'nodeconfig', type_='foreignkey')
    op.drop_constraint(None, 'nodeconfig', type_='foreignkey')
    op.create_foreign_key(op.f('nodeconfig_Workflow_id_fkey'), 'nodeconfig', 'workflow', ['Workflow_id'], ['id'])
    op.drop_column('nodeconfig', 'tool_id')
    op.drop_column('nodeconfig', 'agent_id')
    op.drop_column('nodeconfig', 'workflow_id')
    op.add_column('handoff', sa.Column('Workflow_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'handoff', type_='foreignkey')
    op.create_foreign_key(op.f('handoff_Workflow_id_fkey'), 'handoff', 'workflow', ['Workflow_id'], ['id'])
    op.drop_column('handoff', 'workflow_id')
    op.add_column('agent', sa.Column('config', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('agent_config_fkey'), 'agent', 'nodeconfig', ['config'], ['id'])
    # ### end Alembic commands ###
